name: recommendations-ml-py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - lightfm
  - scikit-surprise
  - pip:
      - implicit==0.7.2
